// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdRTboehasiKUYNTSxULg-wn0ganA1LkA',
    appId: '1:1010841853850:web:4295b653132e3a1113a423',
    messagingSenderId: '1010841853850',
    projectId: 'ecommerce-app-7f8d0',
    authDomain: 'ecommerce-app-7f8d0.firebaseapp.com',
    storageBucket: 'ecommerce-app-7f8d0.appspot.com',
    measurementId: 'G-KJDD5EDLZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACsvVej2qRCxmINs-4Kr3RmQX3rqKc1DA',
    appId: '1:1010841853850:android:f6d0bbbd71d4ab7d13a423',
    messagingSenderId: '1010841853850',
    projectId: 'ecommerce-app-7f8d0',
    storageBucket: 'ecommerce-app-7f8d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIAS1lQ8NR8KzbYmVhb7Zf1d5kp_Ht-5g',
    appId: '1:1010841853850:ios:999584d6deb3f61213a423',
    messagingSenderId: '1010841853850',
    projectId: 'ecommerce-app-7f8d0',
    storageBucket: 'ecommerce-app-7f8d0.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIAS1lQ8NR8KzbYmVhb7Zf1d5kp_Ht-5g',
    appId: '1:1010841853850:ios:999584d6deb3f61213a423',
    messagingSenderId: '1010841853850',
    projectId: 'ecommerce-app-7f8d0',
    storageBucket: 'ecommerce-app-7f8d0.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdRTboehasiKUYNTSxULg-wn0ganA1LkA',
    appId: '1:1010841853850:web:c0005b201c19c7d613a423',
    messagingSenderId: '1010841853850',
    projectId: 'ecommerce-app-7f8d0',
    authDomain: 'ecommerce-app-7f8d0.firebaseapp.com',
    storageBucket: 'ecommerce-app-7f8d0.appspot.com',
    measurementId: 'G-FEBNFV6PE0',
  );
}
